from enum import Enum
DOMAIN = 'flashforge_adventurer_3'
CONF_PRINTERS = '3dprinters'
DEFAULT_PORT = 8899
MODEL_FINDER_ID = 'finder'
MODEL_ADVENTURER_3_ID = 'adventurer_3'
MODEL_ADVENTURER_4_ID = 'adventurer_4'
MODEL_ADVENTURER_5M_ID = 'adventurer_5m'
MODEL_ADVENTURER_5M_PRO_ID = 'adventurer_5m_pro'
MODEL_MAP = {
    MODEL_FINDER_ID: 'Finder',
    MODEL_ADVENTURER_3_ID: 'Adventurer 3',
    MODEL_ADVENTURER_4_ID: 'Adventurer 4',
    MODEL_ADVENTURER_5M_ID: 'Adventurer 5M',
    MODEL_ADVENTURER_5M_PRO_ID: 'Adventurer 5M Pro'
}
BUFFER_SIZE = 1024
TIMEOUT_SECONDS = 5
AVAILABLE_MODELS = [
    MODEL_FINDER_ID,
    MODEL_ADVENTURER_3_ID,
    MODEL_ADVENTURER_4_ID,
    MODEL_ADVENTURER_5M_ID,
    MODEL_ADVENTURER_5M_PRO_ID
]
class PrinterModel(Enum):
    FINDER = MODEL_FINDER_ID
    ADVENTURER_3 = MODEL_ADVENTURER_3_ID
    ADVENTURER_4 = MODEL_ADVENTURER_4_ID
    ADVENTURER_5M = MODEL_ADVENTURER_5M_ID
    ADVENTURER_5M_PRO = MODEL_ADVENTURER_5M_PRO_ID